version: "3.9"

services:
  app:
    environment:
      APP_LOGLEVEL: debug
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  db:
    ports:
      - "5432:5432"

  flower:
    ports:
      - "5555:5555"
